### ISSUE TITLE
add company name to import

### ISSUE THREAD

**Issue by awayand** [datablist/linkedin-contact-importer-airtable-google-sheet-datablist#2]
the extension allows to extract title. any way to add current company name as well?

**Comment by floriandiud** [comment]
Hello awayand,

Thanks for using the extension and for the feedback.
It would be possible yes. I keep it in mind for next time I work on the extension.

Best,
Flo

**Comment by floriandiud** [comment]
Hi @awayand , following @varya pull request, I've pushed a new version that store company name from detail profile page. The new version is 1.0.3 and has been summited to Google Chrome store.
Best,
Florian

**Comment by awayand** [comment]
lovely, thanks a lot, @floriandiud and @varya
